version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 12

  
      # name: version
    commands:
    - npm install --silent --no-progress -g serverless
    - npm --version
    
  pre_build:
    commands:
    - cd services 
    - npm install --silent --no-progress
  build:
    commands:
    #  - serverless deploy --stage dev --region eu-west-1
    - mkdir -p target/stg 
    - mkdir target/prod
    - ls
    - serverless package --package target/stg --stage stg -v -r eu-west-1
    - serverless package --package target/prod --stage prod -v -r eu-west-1
    

artifacts:
  files:
  - services/target/**/*
  - services/serverless.yml
  - services/deploy.sh
