version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 12

  
      # name: version
    commands:
     - npm install --silent --no-progress -g serverless
     - npm --version
    
  pre_build:
    commands:
     - cd services 
     - npm install --silent --no-progress
  build:
    commands:
     - serverless deploy --stage dev --region eu-west-1
    