Resources:
  #DynamoDB Orders Table
  OrdersCatalog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamo-orders}
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1
  MessagesCatalog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamo-messages}
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1