ENV: prod
MESSAGE: 'prod env'
DYNAMO_TABLE_ORDERS: ${self:custom.dynamo-orders} # Reference to Custom Env
SQS_QUEUE_URL: 'https://sqs.${self:provider.region}.amazonaws.com/#{AWS::AccountId}/${self:custom.sqs-logs}'
REGION: ${self:custom.region}
